Adds encodeJpeg and encodePng
tensorflow/tfjs-node pull request #296
Opened 2019-08-15 14:17 UTC by justadudewhohacks

This PR exposes the bindings to tf.io.encode_jpeg and tf.image.encode_png. 

The image decoding operations have been added to tfjs-node a while ago, but currently we still need the node canvas package to save images. That's why I suggest to include these bindings.

2019-08-15 17:19 UTC, kangyizhang requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/296)* status: 0 of 1 approvals obtained (waiting on @justadudewhohacks, @kangyizhang, and @nkreeger)

___
*[src/decode_image.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/296#-LmLD43MBvdDkzSGLBFb:-LmLD43MBvdDkzSGLBFc:br8fq3) ([raw file](https://github.com/tensorflow/tfjs-node/blob/075a8133e03fd4ef95fa58e74309ad7a5e68789f/src/decode_image.ts#L21)):*
> ```XML
> import {ensureTensorflowBackend, nodeBackend} from './ops/op_utils';
> 
> export enum ImageType {
> ```

It's totally not your fault. But ImageType and getImageType() are shared for two files now. For easier readability, could you please rename this file to image.ts and merge encode_image.ts with this file?

Same for decode_image_test.ts and encode_image_test.ts 
___
*[src/encode_image.ts, line 20 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/296#-LmLCLZE-_1qTrfdQrrx:-LmLCLZE-_1qTrfdQrry:b-w73kx) ([raw file](https://github.com/tensorflow/tfjs-node/blob/075a8133e03fd4ef95fa58e74309ad7a5e68789f/src/encode_image.ts#L20)):*
> ```XML
> import {Tensor, Tensor3D, Rank} from '@tensorflow/tfjs-core';
> import {ensureTensorflowBackend, nodeBackend} from './ops/op_utils';
> ```

Can you add some jsdoc describing what this function is doing, what do the params mean. You can grab the info from https://www.tensorflow.org/api_docs/python/tf/io/encode_jpeg and https://www.tensorflow.org/api_docs/python/tf/image/encode_png.

Same for encodePng.
___
*[src/encode_image.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/296#-LmLHA4b2qfOMuSzeJN-:-LmLHA4c21890HMMxtyt:b-z173qz) ([raw file](https://github.com/tensorflow/tfjs-node/blob/075a8133e03fd4ef95fa58e74309ad7a5e68789f/src/encode_image.ts#L34)):*
> ```XML
>       chromaDownsampling, densityUnit, xDensity, yDensity, xmpMetadata);
> 
>     return encodeImage(image, backendEncodeImage);
> ```

Seems like the format is off here. Should be only 2 spaces. 
___
*[src/encode_image_test.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/296#-LmLHJql98_YKU6aP3W3:-LmLHJql98_YKU6aP3W4:b4aejhz) ([raw file](https://github.com/tensorflow/tfjs-node/blob/075a8133e03fd4ef95fa58e74309ad7a5e68789f/src/encode_image_test.ts#L19)):*
> ```XML
> import * as tf from '.';
> import {getImageType, ImageType} from './decode_image';
> ```

Thank you for the comprehensive tests. Can you add validation of encoded value?


<!-- Sent from Reviewable.io -->

2019-08-15 18:50 UTC, kangyizhang requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/296)* status: 0 of 1 approvals obtained (waiting on @justadudewhohacks, @kangyizhang, and @nkreeger)

___
*[binding/tfjs_backend.cc, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/296#-LmLb1xIE6qkTCrbV2LU:-LmLb1xJ-afczhbyxmJg:b-30z1fv) ([raw file](https://github.com/tensorflow/tfjs-node/blob/075a8133e03fd4ef95fa58e74309ad7a5e68789f/binding/tfjs_backend.cc#L90)):*
> ```cpp
>       break;
>     case napi_uint8_array:
>       // TODO: why TF_BOOL?
> ```

The actual value in this tensor is all 0s or 1s, but there is no boolean typed array in N-API. So the values are represented as napi_uint8_array, but actual value is boolean array.


<!-- Sent from Reviewable.io -->

2019-08-19 20:05 UTC, justadudewhohacks commented
Thanks for the quick feedback @kangyizhang. I will make the necessary changes. 

Since all the tfjs-node code also moved to the tfjs mono repo, should I reopen the PR at tfjs?

2019-08-19 20:12 UTC, kangyizhang commented
@justadudewhohacks yes please reopen the PR at tfjs, this repo will be archived and no more sync from here to tfjs, sorry for the inconvenience. I'll close this PR.

Thanks again for adding these ops.

2019-08-19 20:12 UTC, closed without merging